In [2]:
import pandas as pd

In [6]:
hotels = pd.read_csv(r"C:\Users\lucka\Downloads\hotel_booking_data.csv")

In [8]:
hotels.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.0,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.0,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498

In [10]:
# 1. How many rows are there?
len(hotels)

119390

In [21]:
# 2. Missing data and column with most missing values
hotels.isnull().sum().sort_values(ascending=False)

agent                             16340
country                             488
children                              4
lead_time                             0
is_canceled                           0
hotel                                 0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
arrival_date_year                     0
adults                                0
babies                                0
meal                                  0
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
arrival_date_month                    0
previous_bookings_not_canceled        0
reserved_room_type                    0
booking_changes                       0
assigned_room_type                    0
deposit_type                          0
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
name                                  0
email                                 0
phone-number                          0
credit_card                           0
dtype: int64

In [22]:
# 3. Drop the company column
hotels = hotels.drop("company", axis=1)

KeyError: "['company'] not found in axis"

In [24]:
# 4. Top 5 most common country codes
hotels["country"].value_counts().head()

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
Name: count, dtype: int64

In [26]:
# 5. Person who paid the highest ADR
hotels.loc[hotels["adr"].idxmax(), ["name", "adr"]]

name    Daniel Walter
adr            5400.0
Name: 48515, dtype: object

In [28]:
# 6. Mean ADR
hotels["adr"].mean()

np.float64(101.83112153446687)

In [31]:
# 7. Average number of nights
(
    hotels["stays_in_week_nights"] +
    hotels["stays_in_weekend_nights"]
).mean().round(2)

np.float64(3.43)

In [33]:
# 8. Average total cost of stay
(
    hotels["adr"] *
    (hotels["stays_in_week_nights"] + hotels["stays_in_weekend_nights"])
).mean().round(2)

np.float64(357.85)

In [35]:
# 9. Names and emails with exactly 5 special requests
hotels.loc[
    hotels["total_of_special_requests"] == 5,
    ["name", "email"]
]

                          name                          email
7860             Amanda Harper           Amanda.H66@yahoo.com
11125            Laura Sanders      Sanders_Laura@hotmail.com
14596              Tommy Ortiz            Tommy_O@hotmail.com
14921           Gilbert Miller         Miller.Gilbert@aol.com
14922           Timothy Torres         TTorres@protonmail.com
24630          Jennifer Weaver             Jennifer_W@aol.com
27288           Crystal Horton             Crystal.H@mail.com
27477           Brittney Burke       Burke_Brittney16@att.com
29906          Cynthia Cabrera    Cabrera.Cynthia@xfinity.com
29949              Sarah Floyd              Sarah_F@gmail.com
32267           Michelle Villa         Michelle.Villa@aol.com
39027           Nichole Hebert       Hebert.Nichole@gmail.com
39129         Lindsey Mckenzie       Lindsey.Mckenzie@att.com
39525           Ashley Edwards       Edwards.Ashley@yahoo.com
70114       Christopher Torres   Torres.Christopher@gmail.com
78819   Mrs. Tara Sullivan DVM           Mrs..DVM@xfinity.com
78820           Michaela Brown          MichaelaBrown@att.com
78822        Kurt Maldonado MD              KMD15@xfinity.com
97072         Jason Richardson               Jason.R@zoho.com
97099             Terri Hurley            THurley@xfinity.com
97261        Mrs. Caitlin Webb             Mrs._W@comcast.net
98410             Holly Arroyo          Arroyo_Holly@mail.com
98674          Denise Campbell             Denise_C@gmail.com
99887            Michael Smith            Michael.S42@aol.com
99888       Dr. Trevor Sellers                  Dr._S@aol.com
101569            Kayla Murphy         Kayla.Murphy@yahoo.com
102061         Taylor Martinez    Taylor.Martinez@hotmail.com
109511          Charles Wilson       Charles_Wilson@yahoo.com
109590           Tyler Allison         Tyler.A@protonmail.com
110082          Matthew Bailey         Matthew_Bailey@aol.com
110083       Charlotte Acevedo        Charlotte_A@verizon.com
111909         Darrell Brennan  Brennan_Darrell51@hotmail.com
111911          Melinda Jensen         MelindaJensen@zoho.com
113915            Terry Arnold          Arnold.Terry@zoho.com
114770             Mary Nguyen     Nguyen.Mary@protonmail.com
114909          Lindsay Cuevas      Lindsay.Cuevas40@mail.com
116455       Cynthia Hernandez   CynthiaHernandez@xfinity.com
116457          Angela Hawkins             Angela_H@gmail.com
118817              Sue Lawson            Sue.L52@comcast.net
119161         Alyssa Richards        Alyssa_Richards@aol.com

In [37]:
# 10. Percentage of repeat guests
(hotels["is_repeated_guest"].mean() * 100).round(2)

np.float64(3.19)

In [39]:
# 11. Top 5 most common last names
hotels["name"].str.split().str[-1].value_counts().head()

name
Smith       2503
Johnson     1990
Williams    1618
Jones       1434
Brown       1423
Name: count, dtype: int64

In [41]:
# 12. People who booked the most children and babies
family = hotels["children"] + hotels["babies"]

hotels.loc[
    family == family.max(),
    ["name", "children", "babies"]
]

                  name  children  babies
328      Jamie Ramirez      10.0       0
46619  Nicholas Parker       0.0      10

In [43]:
# 13. Top 3 most common phone area codes
hotels["phone-number"].astype(str).str[:3].value_counts().head(3)

phone-number
799    168
185    167
541    166
Name: count, dtype: int64

In [44]:
# 14. Arrivals between 1st and 15th (inclusive)
hotels[
    (hotels["arrival_date_day_of_month"] >= 1) &
    (hotels["arrival_date_day_of_month"] <= 15)
].shape[0]

58152

In [46]:
# 15. Count arrivals by day of the week (Hard Bonus)
import pandas as pd

hotels["arrival_day"] = pd.to_datetime(
    hotels["arrival_date_year"].astype(str) + "-" +
    hotels["arrival_date_month"] + "-" +
    hotels["arrival_date_day_of_month"].astype(str)
)

hotels["arrival_day"].dt.day_name().value_counts()

arrival_day
Friday       19631
Thursday     19254
Monday       18171
Saturday     18055
Wednesday    16139
Sunday       14141
Tuesday      13999
Name: count, dtype: int64